---
name: CapeManager
author: DonSpiderLord
version: 1.1.3
description: Plugin that lets you choose Capes.
main: DonSpiderLord\CapeManager\Main
api: 3.9.3

commands:
  capes:
    description: Choose a Cape!
    usage: /capes

permissions:
  capes.all:
    description: Allows using every Cape
    default: op
    children:
      capes.cmd:
        description: Allows opening the Cape GUI
        default: op
      abstract.cape:
        description: Abstract Cape Perm.
        default: op
      apples.cape:
        description: Apples Cape Perm.
        default: op
      camo.cape:
        description: Camo Cape Perm.
        default: op
      carrot.cape:
        description: Carrot Cape Perm.
        default: op
      chains.cape:
        description: Chains Cape Perm.
        default: op
      dot.cape:
        description: Dot Cape Perm.
        default: op
      duckling.cape:
        description: Duckling Cape Perm.
        default: op
      fusion.cape:
        description: Fusion Cape Perm.
        default: op
      gapple.cape:
        description: Gapple Cape Perm.
        default: op
      gold.cape:
        description: Gold Cape Perm.
        default: op
      greensmog.cape:
        description: Green Smog Cape Perm.
        default: op
      greysmog.cape:
        description: Grey Smog Cape Perm.
        default: op
      hypnosis.cape:
        description: Hypnosis Cape Perm.
        default: op
      lavabucket.cape:
        description: Lava Bucket Cape Perm.
        default: op
      lavawave.cape:
        description: Lava Wave Cape Perm.
        default: op
      melons.cape:
        description: Melon Cape Perm.
        default: op
      mystic.cape:
        description: Mystic Cape Perm.
        default: op
      plane.cape:
        description: Plane Cape Perm.
        default: op
      potato.cape:
        description: Potato Cape Perm.
        default: op
      purply.cape:
        description: Purply Cape Perm.
        default: op
      rainbow.cape:
        description: Rainbow Cape Perm.
        default: op
      sunnyday.cape:
        description: Sunny Day Cape Perm.
        default: op
      sunrise.cape:
        description: Sunrise Cape Perm.
        default: op
      thonk.cape:
        description: Thonk Cape Perm.
        default: op
      tropical.cape:
        description: Tropical Cape Perm.
        default: op
      villager.cape:
        description: Villager Cape Perm.
        default: op
      waves.cape:
        description: Waves Cape Perm.
        default: op
      wood.cape:
        description: Wood Cape Perm.
        default: op
      xcross.cape:
        description: X-Cross Cape Perm.
        default: op
      zebra.cape:
        description: Zebra Cape Perm.
        default: op
...
